Meta:
  num_objs: 2


Environment:
  dimensions: [30, 30]
  ep_length: 40

  timestep_penalty: 0

  global_reward_mode: "Aggregated"

  local_reward_mode: "exponential"
  local_reward_kneecap: 10.0
  local_reward_temp: 2

  observation_mode: "density"
  poi_obs_temp: 2
  agent_obs_temp: 2

  include_location_in_obs: False


POI_Generation:
  mode: "concentric_rings"
  center: [15, 15]

  rings:
    # Easy local reward
    - obj: 0

      num_pois: 4
      radius: 4
      radius_jitter: 1.5
      poi_radius: 1.0
      coupling: 1
      reward: 1
      obs_window: [0, 100]
      repeat: False
      angle_offset_deg: 0

    # Higher-value coordinated exploration
    - obj: 0
      num_pois: 6
      radius: 13
      radius_jitter: 2.5
      poi_radius: 1.0
      coupling: 2
      reward: 3
      obs_window: [0, 100]
      repeat: False
      angle_offset_deg: 30

Agents:
  num_agents: 2
  start_mode: fixed
  starting_locs:
    - [14, 15]
    - [16, 15]

  # Used only if start_mode == random_circle
  start_center: [15, 15]
  start_radius: 1.0
  min_start_separation: 0.5

  num_sensors: [4, 4]

  observation_radii: [6, 6]

  max_step_sizes: [1, 1]